# Generated by Django 4.2.7 on 2023-11-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainingtype',
            fields=[
                ('type_name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('image', models.FileField(max_length=256, upload_to='')),
            ],
        ),
    ]
