[polar_json]
datapath = "{{datapath}}"
datatypes = ["laps", "autoLaps", "samples"]
sport = ["RUNNING", "CYCLING", "OTHER"]

[forerunner_xml]
datapath= '{{datapath}}'
datatypes = ["laps", "samples"]

[garmin_fit]
datapath= '{{datapath}}
datatypes = ["laps", "autoLaps", "samples"]
sport = ["running", "cycling"]
paramnameconversion= {"heartRate": "heart_rate", "startTime":"start_time", "duration":"total_elapsed_time" }
enhanced_record = ['altitude', 'speed']
enhanced_lap = ['max_speed', 'avg_speed']

[mongodb]
database = "{{databasename}}"
password = "{{password}}"
loginname = "{{inlogname}}"
host = "localhost:27017"
timeout=3000
level.database = "person"
level.collection = "year"
level.doc = "training"

[running]
overall_param = ["distance", "speed", "heartRate", "ascent", "descent", "duration", "cadence","startTime", "stopTime"]
lap_param = ["distance", "duration", "cadence", "heartRate", "speed", "ascent", "descent"]

lap_paces.maxeasy = 14
lap_paces.minroadrace = 15.3
lap_paces.maxruninout = 13.2
lap_paces.dspeedinterval = 3


sample_param = ["altitude", "heartRate", "speed", "distance", "recordedRoute"]

[running.sample_paces]
        low_movement = 7
[running.sample_loc]
        develden=[[85575,440076], 700]
        baanbras=[[85085, 449400],600]
        kopjesloop=[[85055, 448570],100]
        schiehaven=[[90775, 435330], 700]
        wippolder=[[86255, 446810],600]
        bergenopzoom=[[81385, 389191],600]
        menmoerhoeve=[[104258, 394390],300]
        sola=[[395744, -72146],15000]
        meijendel=[[82905, 460500],400]
        hermanbavinckstraat=[[95580,436480], 800]
        pac=[[94240, 438880],600]
