version: '3.7'

services:

  polardb:
    image: mongo
    container_name: polardb
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=student
      - MONGO_INITDB_ROOT_PASSWORD=miw3
    volumes:
      - $PWD/mongodb:/app
      - $PWD/mongodb/logs:/var/log/mongodb
    
  barriedb:
    image: mongo
    container_name: barriedb 
    restart: always
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=barriedb
      - MONGO_INITDB_ROOT_PASSWORD=< password >
    volumes:
      - $PWD/mongodb:/app
      - $PWD/mongodb/logs:/var/log/mongodb


